# Generated by Django 5.1 on 2024-08-11 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudios', '0002_planatributos_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
