# Generated by Django 5.1 on 2024-08-11 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudios', '0003_plan_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planatributos',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='Estudios.plan'),
        ),
    ]
